version: '3.8'

services:
  user-service:
    build: ./microservices/user-service
    ports:
      - "5000:5000"

  payment-service:
    build: ./microservices/payment-service
    ports:
      - "5001:5001"

